services:
  frontend:
    build: .
    container_name: planningFrontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - planning-network

  backend:
    build:
      context: ../planningBack   # ✅ Chemin relatif vers le dossier frère
    container_name: planningBackend
    ports:
      - "8000:8000"
    volumes:
      - ../planningBack:/app     # ✅ Volume monté depuis le dossier frère
    restart: always
    networks:
      - planning-network

networks:
  planning-network:
    driver: bridge